2013/02/17 12:12:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "my/service".' in C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('my/service')
#1 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-1.1.13.e9e4a0/demos/webservices/index.php?r=my/service
---
2013/02/17 12:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "myservice".' in C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('myservice')
#1 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-1.1.13.e9e4a0/demos/webservices/index.php?r=myservice
---
2013/02/17 12:15:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mycontroller".' in C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('mycontroller')
#1 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-1.1.13.e9e4a0/demos/webservices/index.php?r=mycontroller
---
2013/02/17 12:16:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mycontroller".' in C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('mycontroller')
#1 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-1.1.13.e9e4a0/demos/webservices/index.php?r=mycontroller
---
2013/02/17 12:23:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "webcontroller".' in C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('webcontroller')
#1 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-1.1.13.e9e4a0/demos/webservices/index.php?r=webcontroller
---
2013/02/17 12:25:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "my/services".' in C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('my/services')
#1 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-1.1.13.e9e4a0/demos/webservices/index.php?r=my/services
---
2013/02/17 12:25:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "my/service".' in C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('my/service')
#1 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii-1.1.13.e9e4a0/demos/webservices/index.php?r=my/service
---
2013/02/17 22:35:43 [error] [exception.CDbException] exception 'CDbException' with message 'Table "user" does not have a column named "username".' in C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\db\schema\CDbCommandBuilder.php:591
Stack trace:
#0 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\db\ar\CActiveRecord.php(1464): CDbCommandBuilder->createColumnCriteria(Object(CPgsqlTableSchema), Array, '', Array, '"t".')
#1 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\protected\components\UserIdentity.php(21): CActiveRecord->findByAttributes(Array)
#2 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yii-1.1.13.e9e4a0/demos/webservices/index.php/site/login
HTTP_REFERER=http://localhost/yii-1.1.13.e9e4a0/demos/webservices/index.php/site/login
---
2013/02/17 22:40:44 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity._id" is not defined.' in C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CComponent.php:173
Stack trace:
#0 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\protected\components\UserIdentity.php(29): CComponent->__set('_id', 1)
#1 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#13 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/yii-1.1.13.e9e4a0/demos/webservices/index.php/site/login
HTTP_REFERER=http://localhost/yii-1.1.13.e9e4a0/demos/webservices/index.php/site/login
---
2013/02/17 22:42:26 [error] [exception.CException] exception 'CException' with message 'Property "User.title" is not defined.' in C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CComponent.php:130
Stack trace:
#0 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\db\ar\CActiveRecord.php(143): CComponent->__get('title')
#1 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\protected\components\UserIdentity.php(30): CActiveRecord->__get('title')
#2 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\framework\base\CApplication.php(169): CWebApplication->processRequest()
#14 C:\inetpub\wwwroot\yii-1.1.13.e9e4a0\demos\webservices\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yii-1.1.13.e9e4a0/demos/webservices/index.php/site/login
HTTP_REFERER=http://localhost/yii-1.1.13.e9e4a0/demos/webservices/index.php/site/login
---
